# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: UnblockOz - Evade Internet Censorship
email: hello@cryptoaustralia.org.au
description: > # this means to ignore newlines until "baseurl:"
  Evade Internet Censorship in Australia. Unblock websites with Tor, DNS and VPN services.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://unblockoz.org"
twitter_username: CryptoAustralia
github_username:  cryptoaustralia

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - [vendor]
  - LICENSE.md
google_analytics: UA-87384200-4
